### ISSUE TITLE
train.py падает при запуске

### ISSUE THREAD

**Issue by kuzmichevdima** [aleksss123/text-generator#14]
запускаю так: python3 train.py --input_dir ../small_test_only --model model

падает с ошибкой
  File "train.py", line 226, in <module>
    prepare_input()
  File "train.py", line 30, in prepare_input
    os.chdir(args.model)
FileNotFoundError: [Errno 2] No such file or directory: 'model'

**Comment by aleksss123** [comment]
если изменять стандартный путь записи директории model, то в таком случае нужно прописать полный путь до папки, в которую вы хотите сохранить модель
т.е. python3 train.py --input_dir ../small_test_only --model ../Desktop/some_dir
