### ISSUE TITLE
start, end

### ISSUE THREAD

**Issue by kuzmichevdima** [aleksss123/text-generator#2]
https://github.com/aleksss123/text-generator/blob/5ab8f8cec97cb1c36a9920c9db233b657a72b6cd/train.py#L22

https://github.com/aleksss123/text-generator/blob/5ab8f8cec97cb1c36a9920c9db233b657a72b6cd/train.py#L39

избавься от костылей *start*, *end*

**Comment by aleksss123** [comment]
это не баг, а фича

**Comment by kuzmichevdima** [comment]
ввод из консоли прерывается ctrl+x. Зачем придумывать велосипед?

**Comment by aleksss123** [comment]
оу. не знал
