### ISSUE TITLE
скобки вокруг if

### ISSUE THREAD

**Issue by kuzmichevdima** [aleksss123/text-generator#6]
https://github.com/aleksss123/text-generator/blob/5ab8f8cec97cb1c36a9920c9db233b657a72b6cd/generate.py#L30

https://github.com/aleksss123/text-generator/blob/5ab8f8cec97cb1c36a9920c9db233b657a72b6cd/generate.py#L35

в питоне не нужно ставить скобки вокруг простых ifов

**Comment by aleksss123** [comment]
ок
