### ISSUE TITLE
специальное поведение для захардкоженного файла

### ISSUE THREAD

**Issue by kuzmichevdima** [aleksss123/text-generator#8]
https://github.com/aleksss123/text-generator/blob/12d666491f858478c8b842521194971e18b9e07f/train.py#L33

https://github.com/aleksss123/text-generator/blob/12d666491f858478c8b842521194971e18b9e07f/train.py#L46

Чем это оправдывается?

**Comment by aleksss123** [comment]
поясни, пожалуйста
вопрос "зачем я использую этот файл"?
